FROM amazonlinux

ENV HOME=/root

WORKDIR /root

RUN yum update -y
RUN yum groupinstall -y 'Development Tools'
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum install -y tree readline-devel bzip2-devel sqlite-devel openssl-devel \
  awscli nodejs which

RUN amazon-linux-extras install golang1.11 rust1 vim

RUN yum install -y rsync
