name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Base Docker image
      run: docker build -t eph-nvim/base:latest -f .config/docker/Dockerfile.nvim.base .
