name: Docker Images

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}

on:
  push:
    paths:
      - "config/docker"

jobs:
  binaries_container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: login
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
      - name: build bins
        run: docker build -t evanharmon/eph-bin:latest - < .config/docker/Dockerfile.binaries.base
      - name: push bins
        run: docker push evanharmon/eph-bin:latest
  pyenv_container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: login
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
      - name: build python
        run: docker build -t evanharmon/eph-python:latest -f .config/docker/Dockerfile.python.base .
      - name: push python
        run: docker push evanharmon/eph-python:latest
  # rvm_container:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@master
  #     - name: login
  #       run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
  #     - name: build ruby
  #       run: docker build -t evanharmon/eph-ruby:latest -f .config/docker/Dockerfile.ruby.base .
  #     - name: push ruby
  #       run: docker push evanharmon/eph-ruby:latest
  # golang_container:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@master
  #     - name: login
  #       run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
  #     - name: build go
  #       run: docker build -t evanharmon/eph-golang:latest -f .config/docker/Dockerfile.golang.base .
  #     - name: push go
  #       run: docker push evanharmon/eph-golang:latest
  # aws_cpp_sdks_container:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@master
  #     - name: login
  #       run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
  #     - name: build aws cpp sdks
  #       run: docker build -t evanharmon/eph-aws-sdks:latest -f .config/docker/Dockerfile.aws-sdks .
  #     - name: push
  #       run: docker push evanharmon/eph-aws-sdks:latest
  # final_container:
  #   needs:
  #     [
  #       binaries_container,
  #       pyenv_container,
  #       rvm_container,
  #       golang_container,
  #       aws_cpp_sdks_container,
  #     ]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@master
  #     # AMAZON LINUX2
  #     - name: build linux
  #       run: docker build -t evanharmon/eph-amazonlinux:latest -f .config/docker/Dockerfile.amazonlinux.devtools .
  #     - name: login
  #       run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
  #     - name: push linux
  #       run: docker push evanharmon/eph-amazonlinux:latest
  #     - name: build nvim
  #       run: docker build -t evanharmon/eph-nvim:latest -f .config/docker/Dockerfile.nvim.base .
  #     - name: push nvim
  #       run: docker push evanharmon/eph-nvim:latest
